config/routes.rb
Rails.application.routes.draw do

  resources :cryptos, only: [:index, :show, :create] do
    resources :posts, only: [:create]
    resources :votes, only: [:create]
    resources :favorites, only: [:create, :edit, :update, :destroy]
    resources :alert_prices, only: [:create, :edit, :update, :destroy]
  end

  resources :posts, only: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  resources :notifications, only: [:create, :update, :destroy]

  resources :notifications, only: [] do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :profiles, only: [:show, :update] do
    resources :avatars, only: [:create]
    collection do
      get :search
    end
    member do
      delete :delete_user
    end
  end
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check
  get 'termsofuse', to: 'static_pages#termsofuse'
  get 'faq', to: 'static_pages#faq'
  get "privacy_policy", to: "static_pages#privacy_policy"
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get 'contact/send_message', to: 'static_pages#send_message'
  get 'credit', to: 'static_pages#credit'


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cryptos#index"
  
end

app/controllers/profiles_controller.rb
  class ProfilesController < ApplicationController
    before_action :authenticate_user!
  
    def show
      @user = current_user
    end
  
    def update
      @user = current_user
    
      new_username = params[:user][:username]

      if User.exists?(username: new_username) && new_username != @user.username
        flash[:alert] = "This username is already taken. Please choose another one."
        render :show and return
      end

      if @user.update_without_password(user_params)
        flash[:notice] = "Username updated successfully!"
        redirect_to profile_path
      else
        flash[:alert] = @user.errors.full_messages.join(", ")
        render :show
      end
    end
    
    def search
      @user = current_user

      if params[:query].present?
        query = "%#{params[:query]}%"
        @searched_users = User.where("email ILIKE ? OR username ILIKE ?", query, query)
      else
        @searched_users = []
        flash[:alert] = "Please enter a value to search."
      end

      respond_to do |format|
        format.turbo_stream { render :search }
        format.html { render :show }
      end
    end
  

    def delete_user
      
      user = User.find(params[:id])

      if current_user.is_admin == true
        if user.destroy
          flash[:success] = "User successfully deleted."
        else
          flash[:error] = "An error occurred during deletion."
        end
      else
        flash[:alert] = "Access denied."
      end

      redirect_to profile_path
    end

    private
  
    def user_params
      params.require(:user).permit(:username)
    end
  end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<%= javascript_include_tag 'userimg' %>
<%= render 'shared/navbar' %>
<%= render 'shared/flash' %>

<%= button_to root_path, method: :get, class: 'btn-home act profil-home' do %>
  <%= image_tag "arrowleft.png", alt: "arrow-left", class: "icone" %>
  Back to Home
<% end %>

<div class="body-flex">
  <div class="profile-card">
    <h3>My Profile</h3>
    <div class="profile-info gradient-box">

      <div class="header-profil">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, alt: "avatar", class: "user-avatar-profil" %>
        <% else %>
          <%= image_tag "memoji.png", alt: "user", class: "user-avatar-profil" %>
        <% end %>
        <p><%= @user.username %></p>
        <%= image_tag "edit-icon.png", alt: "edit username", class: "edit-username-icon", id: "open-username-popup" %>
      </div>

      <div id="username-popup" class="popup hidden">
        <div class="popup-content gradient-box">
          <div class="header-popup">
            <%= image_tag "close.png", alt: "close", class: "close-img", id: "close-username-popup" %>
          </div>
          <p class="change-text">Change your username</p>
          <%= form_for @user, url: profile_path(@user), method: :patch, html: { class: "username-form" } do |f| %>
            <div class="field">
              <%= f.label :username, "New Username", class: "username-label" %>
              <div class="input-container">
                <%= image_tag "edit-icon.png", alt: "edit icon", class: "edit-icon" %>
                <%= f.text_field :username, placeholder: "Enter new username", class: "username-input" %>
              </div>
            </div>
            <div class="actions">
              <%= f.submit "Save", class: "btn-save" %>
            </div>
          <% end %>
        </div>
      </div>

      <p class="email-profil">
        <%= image_tag "mail.png", alt: "mail", class: "icone-mail" %>
        <%= @user.email %>
      </p>

      <div class="profile-actions">
        <%= button_to "Edit Profile", edit_user_registration_path, method: :get, class: "btn-edit-profile" %>
      </div>

      <%= form_with url: user_registration_path, method: :delete, class: "delete-account-form" do %>
        <%= submit_tag "Delete Account", data: { confirm: "Are you sure you want to delete your account?" }, class: "btn-delete-profile" %>
      <% end %>
    </div>
  </div>

  <div class="image-profil">
    <%= image_tag "userprofile.png", alt: "img-profil", class: "profil-img" %>
  </div>
</div>

<div class="body-flex">
  <div class="admin-card">
    <% if current_user.is_admin == true %>
      <h3>Admin Panel</h3>
      <div class="profile-info gradient-box">

        <%= form_with url: search_profiles_path, method: :get, local: true, data: { turbo_frame: "search_results" } do |form| %>
          <div class="change-text-admin">
            <%= form.label :query, "Search user for delete :" %>
            </br>
            </br>
            <%= form.text_field :query, placeholder: "Email or Username", class: "input-contact" %>
            </br>
            <%= form.submit "Search", class: "btn-save" %>
          </div>
        <% end %>

        <turbo-frame id="search_results">
          <% if @searched_users.present? %>
            <ul>
              <% @searched_users.each do |user| %>
                <li class="email-profil">
                  <%= user.email %>(<%= user.username %>)
                  <% if user.email != current_user.email %>
                    <%= button_to "Delete user", delete_user_profile_path(user), method: :delete, data: { confirm: "Are your sure ?" }, class: "btn-delete-user" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% elsif defined?(@searched_users) %>
            <p class="email-profil">No users found.</p>
          <% end %>
        </turbo-frame>
      </div>
    <% end %>
  </div>
</div>