config/routes.rb
Rails.application.routes.draw do

  resources :cryptos, only: [:index, :show, :create] do
    resources :posts, only: [:create]
    resources :votes, only: [:create]
    resources :favorites, only: [:create, :edit, :update, :destroy]
    resources :alert_prices, only: [:create, :edit, :update, :destroy]
  end

  resources :posts, only: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  resources :notifications, only: [:create, :update, :destroy]

  resources :notifications, only: [] do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :profiles, only: [:show, :update] do
    resources :avatars, only: [:create]
    collection do
      get :search
    end
    member do
      delete :delete_user
    end
  end
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check
  get 'termsofuse', to: 'static_pages#termsofuse'
  get 'faq', to: 'static_pages#faq'
  get "privacy_policy", to: "static_pages#privacy_policy"
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get 'contact/send_message', to: 'static_pages#send_message'
  get 'credit', to: 'static_pages#credit'


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cryptos#index"
  
end

app/models/alert_price.rb
class AlertPrice < ApplicationRecord
  belongs_to :user
  belongs_to :crypto

  validates :price_up, numericality: { allow_nil: true }
  validates :price_down, numericality: { allow_nil: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true

  before_save :filter_profanity

  private

  def filter_profanity
    self.content = $profanity_filter.sanitize(content)
  end

end

app/models/crypto.rb
class Crypto < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user  # this relationship represents the users who have favorited this crypto.

  include PgSearch::Model

  pg_search_scope :search_by_name_or_symbol,
    against: [:name, :symbol],
    using: {
      tsearch: { prefix: true }
    }
  has_many :posts, dependent: :destroy
  has_many :alert_prices, dependent: :destroy

  validates :name, :symbol, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def bullish_percentage
    total_votes = votes.count
    return 0 if total_votes.zero?
    (votes.where(is_bullished: true).count.to_f / total_votes * 100).round(1)
  end

  def bearish_percentage
    total_votes = votes.count
    return 0 if total_votes.zero?
    100 -  bullish_percentage
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :crypto

  validates :crypto_id, uniqueness: { scope: :user_id }

  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def total_price
    quantity * crypto.price
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :crypto
  has_many :comments, dependent: :destroy

  validates :content, presence: true

  before_save :filter_profanity

  private

  def filter_profanity
    self.content = $profanity_filter.sanitize(content)
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_create :generate_random_username
  
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :cryptos, through: :votes
  has_many :votes_histories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  has_many :favorites, dependent: :destroy
  has_many :favorite_cryptos, through: :favorites, source: :crypto # this relationship represents the cryptos that the user has marked as favorites
  has_many :notifications, dependent: :destroy
  has_many :alert_prices, dependent: :destroy
  
  after_create :welcome_send
  after_destroy :send_account_deleted_email

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  validates :accepted_cgu, inclusion: { in: [true], message: "Please accept the Terms of Service to continue." }, on: :create
  validates :accepted_privacy_policy, inclusion: { in: [true], message: "Please accept the Privacy Policy to continue." }, on: :create
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, if: :password_required?


  before_create :set_accepted_at

  private

  def set_accepted_at
    self.accepted_at = Time.current if accepted_cgu && accepted_privacy_policy
  end

  def generate_random_username
    loop do
      self.username = "@trader_#{rand(1000..999999)}"
      break unless self.class.exists?(username: username)
    end
  end

  def password_required?
    new_record? || password.present?
  end

  def send_account_deleted_email
    UserMailer.account_deleted_email(self).deliver_now
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :crypto
  belongs_to :user
end

app/models/votes_history.rb
class VotesHistory < ApplicationRecord
  belongs_to :crypto
  belongs_to :user

  validates :user_id, uniqueness: { scope: [ :crypto_id, :voted_at ] }
end

app/helpers/alert_prices_helper.rb
module AlertPricesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "CoinTribe" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/fav.png" type="image/png">
    <link rel="icon" href="/fav.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/fav.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_btndown.html.erb
<%= button_to crypto_votes_path(@crypto, is_bullished: false), method: :post, class: 'buttondown' do %>
<span class="fold">
</span>
<div class="points_wrapper">
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
</div>
<span class="inner">
    <svg class="icon" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5">
        <polyline points="11.36 22.63 11.36 14.36 2.55 14.36 13.18 1.37 13.18 9.64 21.45 9.64 10.82 22.63"></polyline>
    </svg>
    Bearish
</span>
<% end %>

app/views/shared/_btnup.html.erb
<%= button_to crypto_votes_path(@crypto, is_bullished: true), method: :post, class: 'buttonup' do %>
  <span class="fold"></span>

  <div class="points_wrapper">
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
    <i class="point"></i>
  </div>

  <span class="inner">
    <svg
      class="icon"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2.5"
    >
      <polyline
        points="13.18 1.37 13.18 9.64 21.45 9.64 10.82 22.63 10.82 14.36 2.55 14.36 13.18 1.37"
      ></polyline>
    </svg>
    Bullish
  </span>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="flash-message <% key %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to 'Privacy Policy', privacy_policy_path, class: 'link-footer' %>
<%= link_to 'T&Cs', termsofuse_path, class: 'link-footer' %>
<%= link_to 'Contact', contact_path, class: 'link-footer' %>
<%= link_to 'About', about_path, class: 'link-footer' %>
<%= link_to 'FAQ', faq_path, class: 'link-footer' %>

<p class="copyright-container">© 2024 <%= link_to 'CoinTribe', credit_path, class: 'link-footer' %> . All rights reserved.</p>

app/views/shared/_navbar.html.erb
<%= javascript_include_tag 'navbarSearch' %>
<%= javascript_include_tag 'navbarProfil' %>
<%= javascript_include_tag 'notif' %>

<nav>
  <div class="logo-container">
    <%= link_to image_tag(asset_path("logo-navbar.png"), alt: "Logo Voting", class: "navbar-logo"), root_path, class: "navbar-logo-link" %>
  </div>

  <div class="navbar-search">
    <div data-controller="search" class="search-section-nav">
      <div class="search-home-nav">
        <%= image_tag "search-icon.png", alt: "search-icone", class: "icon-search-nav" %>
        <%= text_field_tag :search, nil, id: "search-input-navbar", class: "input-nav", placeholder: "Bitcoin...", data: { action: "input->search#search", target: "search.input" } %>
      </div>
      <div id="search-results" class="gradient-box nav-result" data-search-target="results"></div>
    </div>
  </div>

  
  <% if user_signed_in? %>
    <%= button_to mark_as_read_notifications_path, method: :post, class: "btn-notif", data: { turbo: true } do %>
      <% if current_user.notifications.where(is_read?: false).exists? %>
        <%= image_tag "new-notif.png", alt: "notif", class: "icone-notif" %>
      <% else %>
        <%= image_tag "notif.png", alt: "notif", class: "icone-notif" %>
      <% end %>
    <% end %>
      
    <div class="notif-popup">
      <div id="notifications_list">
        <% current_user.notifications.reverse.each do |notif| %>
          <div class="notif <%= 'read' if notif.is_read? %>">
            <span class="title-notif">
              <span><%= notif.title %></span>
              <span class="date-notif"><%= notif.created_at.strftime("%d/%m %H:%M") %></span>
            </span>
            <span class="text-notif"><%= notif.content %></span>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="navbar-actions">
    <button id="profil-btn" class="act">
      <% if user_signed_in? %>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, alt: "avatar", class: "user-icone" %>
        <% else %>
          <%= image_tag "memoji.png", alt: "user", class: "user-icone" %>
          <% if current_user.username.present? %>
            <p class="pseudouser-btn"><%= current_user.username %></p>
          <% end %>
        <% end %>
      <% else %>
        <%= image_tag "profil.png", alt: "setting", class: "icone-nav" %>
      <% end %>
    </button>
  </div>
</nav>

<div id="profil">
  <div class="headerprofil">
    <div id="closeBtnProfil" class="btn-menu act" role="button">
      <%= image_tag "arrowright.png", alt: "arrow-right", class: "icone-arrow" %>
    </div>

    <% if user_signed_in? %>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, alt: "avatar", class: "user-icone" %>
        <% else %>
          <%= image_tag "memoji.png", alt: "user", class: "user-icone" %>
          <% if current_user.username.present? %>
            <p class="pseudouser"><%= current_user.username %></p>
          <% end %>
        <% end %>
      <% end %>

    <% if user_signed_in? %>
      <%= button_to profile_path(current_user), method: :get, data: { turbo: false }, class: 'btn-menu act' do %>
        <%= image_tag "profil.png", alt: "setting", class: "icone-nav" %>
      <% end %>

      <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn-menu act delog' do %>
        <%= image_tag "power.png", alt: "power", class: "icone-nav" %>
      <% end %>
    <% end %>
  </div>

  <div class="container-btn-nav">
    <% if !user_signed_in? %>
      <%= button_to "Sign in", new_user_session_path, class: "btn-login-nav act" %>
      <%= button_to "Sign up", new_user_registration_path, method: :get, class: "btn-new-nav act" %>
    <% end %>
  </div>

  <div class="favorites-container">
    <% if user_signed_in? %>
      <div class="total-balance"> 
       <span class="info-text-favorite">Total Balance</span>
        <span class="total-favorite"><%= number_to_currency(@total_balance) %></span>
      </div>

      <div class="favorites-listing">
        <% if @favorites_for_menu.any? %>
          <% @favorites_for_menu.each do |favorite| %>
            <div class="favorite-line">
              <div class="fav-left">
                <div class="fav-logo">
                  <%= image_tag(favorite.crypto.logo_url, alt: 'crypto-logo', class: 'crypto-logo') %>
                  </div>
                  <div class="fav-info">
                <span class="fav-symbol"><%= favorite.crypto.symbol %></span>
                 </br>
                  <span class="info-text-favorite">$<%= favorite.crypto.price.round(2) %></span>
                    <% variation = favorite.crypto.variation_24h %>
                    <% if variation >= 0 %>
                      <span class="positif">+<%= number_to_human(variation) %>%</span>
                    <% else %>
                      <span class="negatif"><%= number_to_human(variation) %>%</span>
                    <% end %>
               </div>
               </div>
              <div class="fav-right">
                <span><%= favorite.quantity %></span>
               
                <span class="info-text-favorite"><%= number_to_currency(favorite.quantity * favorite.crypto.price) %></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="footer-container">
    <%= render 'shared/footer' %>
  </div>
</div>