config/routes.rb
Rails.application.routes.draw do

  resources :cryptos, only: [:index, :show, :create] do
    resources :posts, only: [:create]
    resources :votes, only: [:create]
    resources :favorites, only: [:create, :edit, :update, :destroy]
    resources :alert_prices, only: [:create, :edit, :update, :destroy]
  end

  resources :posts, only: [:destroy] do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  resources :notifications, only: [:create, :update, :destroy]

  resources :notifications, only: [] do
    collection do
      post :mark_as_read
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :profiles, only: [:show, :update] do
    resources :avatars, only: [:create]
    collection do
      get :search
    end
    member do
      delete :delete_user
    end
  end
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  get "up" => "rails/health#show", as: :rails_health_check
  get 'termsofuse', to: 'static_pages#termsofuse'
  get 'faq', to: 'static_pages#faq'
  get "privacy_policy", to: "static_pages#privacy_policy"
  get 'contact', to: 'static_pages#contact'
  get 'about', to: 'static_pages#about'
  get 'contact/send_message', to: 'static_pages#send_message'
  get 'credit', to: 'static_pages#credit'


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "cryptos#index"
  
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user  # this relationship represents the users who have favorited this crypto.

  include PgSearch::Model

  pg_search_scope :search_by_name_or_symbol,
    against: [:name, :symbol],
    using: {
      tsearch: { prefix: true }
    }
  has_many :posts, dependent: :destroy
  has_many :alert_prices, dependent: :destroy

  validates :name, :symbol, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def bullish_percentage
    total_votes = votes.count
    return 0 if total_votes.zero?
    (votes.where(is_bullished: true).count.to_f / total_votes * 100).round(1)
  end

  def bearish_percentage
    total_votes = votes.count
    return 0 if total_votes.zero?
    100 -  bullish_percentage
  end

end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  
  def index
    @user = current_user
    @new_cryptos = Crypto.order(created_at: :desc).limit(5)
    if params[:search].present?
      @cryptos = Crypto.search_by_name_or_symbol(params[:search])
    else
      @cryptos = Crypto.limit(5)
    end

    respond_to do |format|
      format.html
      format.json { render json: @cryptos.pluck(:id, :name, :symbol, :price, :variation_24h, :logo_url) }
    end
  end

  def show
    @user = current_user
    @crypto = Crypto.find(params[:id])
    @posts = @crypto.posts.includes(:comments).order(created_at: :desc)
    @post = Post.new
    @comment = Comment.new
    @favorite = Favorite.find_by(user: current_user, crypto: @crypto) || Favorite.new(crypto: @crypto, user: current_user)
    @voteshistory_by_day = VotesHistory.where(crypto_id: @crypto.id)
                                        .group("DATE(created_at)", "is_bullished")
                                      .count
    @alert_price = AlertPrice.find_by(user: current_user, crypto: @crypto) || AlertPrice.new(crypto: @crypto, user: current_user) if user_signed_in?
    
  end
  
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/views/cryptos/index.html.erb
<%= javascript_include_tag 'homeSearch' %>

<body>
  <%= render 'shared/navbar' %>

  <div class="body-flex">

    <div class="left-section-home">
      <div>
        <h3>News</h3>
        <div class="news-container gradient-box">
          <div class="tradingview-widget-container">
            <div class="tradingview-widget-container__widget"></div>
            <div class="tradingview-widget-copyright"></div>
            <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-timeline.js" async>
              {
                "feedMode": "all_symbols",
                "isTransparent": true,
                "displayMode": "adaptive",
                "width": "100%",
                "height": "100%",
                "colorTheme": "dark",
                "locale": "en"
              }
            </script>
          </div>
        </div>
      </div>

      <div>
        <div class="new-container">
          <h3>News Token Listing</h3>
          <div class="gradient-box new-box">
            <% if @new_cryptos.present? && @new_cryptos.last(2).any? %>
              <% @new_cryptos.last(2).each do |crypto| %>
                <% if crypto.present? && crypto.logo_url.present? && crypto.price.present? %>
                  <%= button_to crypto_path(crypto), method: :get, class: 'crypto-link' do %>
                    <div class="logo-wrapper">
                      <%= image_tag(crypto.logo_url, alt: "crypto-logo", class: "crypto-logo") %>
                      <div class="name-symbol">
                        <span class="name-crypto-new"><%= crypto.name %></span>
                        <span class="symbol-new"><%= crypto.symbol %></span>
                      </div>
                    </div>
                    <p>
                      <span class="price-new"><%= number_to_currency(crypto.price, unit: "$") %></span>
                      <% variation = crypto.variation_24h || 0 %>
                      <% if variation >= 0 %>
                        <span class="positif">
                          +<%= number_to_human(variation) %>%
                        </span>
                      <% else %>
                        <span class="negatif">
                          <%= number_to_human(variation) %>%
                        </span>
                      <% end %>
                    </p>
                  <% end %>
                <% end %>
              <% end %>
            <% else %>
              <p>No new cryptos available.</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="right-section-home">
      <%= image_tag "cryptoback.png", alt: "background-crypto", class: "crypto-background" %>

      <div class="container-search">
        <h3 class="title-search">Vote, discuss, and track</br> your cryptos in real time.</h3>
        <div data-controller="search" class="search-section">
          <div class="search-home">
            <%= image_tag "search-icon.png", alt: "search-icone", class: "icon-search" %>
            <%= text_field_tag :search, nil, id: "search-input-home", class: "input-home", placeholder: "Search Your Crypto...", 
              data: { action: "input->search#search", target: "search.input" } %>
          </div>
          <div id="search-results" class="gradient-box result" data-search-target="results"></div>
        </div>
      </div>
    </div>

  </div>
</body>

app/views/cryptos/show.html.erb
<%= javascript_include_tag 'chart' %>
<%= javascript_include_tag 'post' %>
<%= javascript_include_tag 'load' %>
<%= javascript_include_tag 'timechoice' %>
<%= javascript_include_tag 'https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js', defer: true %>
<%= javascript_include_tag 'favorites' %>
<%= javascript_include_tag 'priceAlert' %>
<%= javascript_include_tag 'comment' %>

<%= render 'shared/navbar' %>
<%= render 'shared/flash' %>

<div class="body-flex-show">

  <div class="chart-section">
    <%= button_to root_path, method: :get, class: 'btn-home-go act' do %>
      <%= image_tag 'arrowleft.png', alt: 'arrow-left', class: 'icone' %>
      Back to Home
    <% end %>

    <div class="card-chart">
      <div class="header-card">
        <div class="info-card">
          <%= image_tag(@crypto.logo_url, alt: 'crypto-logo', class: 'crypto-logo') %>
          <div class="name-symbol">
            <span class="price-card">
              $<%= @crypto.price.round(2) %>
              <% variation = @crypto.variation_24h %>
              <% if variation >= 0 %>
                <span class="positif">+<%= number_to_human(variation) %>%</span>
              <% else %>
                <span class="negatif"><%= number_to_human(variation) %>%</span>
              <% end %>
            </span>
            <span class="symbol" id="crypto-symbol"><%= @crypto.symbol %></span>
          </div>
        </div>

        <div class="btn-card">
          <div role="button" id="btn-1m" class="choice">
            <p>1m</p>
          </div>
          <div role="button" id="btn-15m" class="choice">
            <p>15m</p>
          </div>
          <div role="button" id="btn-1h" class="choice">
            <p>1h</p>
          </div>
          <div role="button" id="btn-4h" class="choice">
            <p>4h</p>
          </div>
          <div role="button" id="btn-1d-main" class="choice">
            <p id="time-label">1d</p>
            <%= image_tag "arrowbottom.png", alt: "arrow", class: "arrow-bottom" %>
            <div id="time-options">
              <button id="btn-6h">
                <span>6h</span>
              </button>
              <button id="btn-12h">
                <span>12h</span>
              </button>
              <button id="btn-1d">
                <span>1d</span>
              </button>
            </div>
          </div>
        </div>

        <div class="container-favorites-alert">
          <% if user_signed_in? %>
            <% if @favorite.is_favorite %>
              <%= image_tag "favorites-true.png", alt: "In Favorites", class: "favorites-img", id: "open-favorite-popup" %>
            <% else %>
              <%= image_tag "favorites-false.png", alt: "Add to Favorites", class: "favorites-img", id: "open-favorite-popup" %>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <% if @alert_price.id %>
              <%= image_tag "alert-red.png", alt: "In Favorites", class: "alert-img", id: "open-price-alert-popup" %>
            <% else %>
              <%= image_tag "alert.png", alt: "In Favorites", class: "alert-img", id: "open-price-alert-popup" %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div id="chart"></div>
      <div class="info-crypto">
        <div class="container-volume">
          <p class="info-text">Volumes (24h):</p>
          <p class="text-info-card">$<%= @crypto.volume_24h %></p>
        </div>
        <div class="container-price">
          <p class="info-text">Price:</p>
          <p>
            <span class="text-info-card"> $<%= @crypto.price.round(2) %></span>
            <% variation = @crypto.variation_24h.round(2) %>
            <% if variation >= 0 %>
              <span class="positif">+<%= number_to_human(variation) %>%</span>
            <% else %>
              <span class="negatif"><%= number_to_human(variation) %>%</span>
            <% end %>
          </p>
        </div>
      </div>
    </div>

  </div>

  <div class="post-section">
    <%= render 'shared/flash' %>

    <div id="posts_container">
      <% @posts.each do |post| %>
        <div id="post_<%= post.id %>" class="post">
          <div class="post-line">
            <div class="header-post">
              <div class="user-post">
                <%= image_tag "memoji.png", alt: "user", class: "user-icone" %>
                <p class="username-post"><%= post.user.username %></p>
                <% if post.user == current_user %>
                  <%= button_to post_path(post), method: :delete, class: 'btn-delete-comment', data: { confirm: "Are you sure you want to delete this post?" } do %>
                    <%= image_tag 'delete.png', alt: 'Delete', class: 'delete-icone' %>
                  <% end %>
                <% end %>
              </div>
              <p class="time-post">
                <%= image_tag "time.png", alt: "time", class: "time-icone" %>
                <%= time_ago_in_words(post.created_at) %> ago
              </p>
            </div>
            <div class="content-post-container">
              <p class="content-post"><%= post.content %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>